version: '3'

services:

  vide-json:
    build: .
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dconfig.file=/workspace/application-prod.properties", "-jar", "vibe-json.jar"]
    volumes:
      - './src/main/resources/application-prod.properties:/workspace/application-prod.properties'
    restart: always
    container_name: vibe-json
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PG_DATASOURCE_URL=jdbc:postgresql://vibe-db:5432/vibejson
      - PG_NAME=pgadmin
      - PG_PASS=pgadmin
      - OPENAI_API_KEY
    tty: true
    depends_on:
      - vibe-db

  vibe-db:
    build:
      dockerfile: ./Dockerfile
      context: postgres
    restart: always
    container_name: vibe-db
    ports:
      - "25433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuramshin.py@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5051:80"
    depends_on:
      - vibe-db

volumes:
  postgres_data:
  pgadmin_data:
    driver: local